%Your Implementation of Newton's method
%INPUTS:
%fun: the mathematical function for which we want to compute the root
%   note that the output of fun may include the derivative
%   i.e. [fval,dfdx] = fun(x)
%   or not, i.e. fval = fun(x)
%x_guess the initial guess for Newton's method
%solver_params: a MATLAB struct containing solver settings
%   solver_params.dxmin: terminate early if |x_{i+1}-x_{i}|<dxmin
%   solver_params.ftol: terminate early if |f(x_i)|<ftol
%   solver_params.max_iter: maximum number of iterations allowed
%   solver_params.dxmax: terminate early if |x_{i+1}-x_{i}|>dxmax
%       (meaning that jacobian is probably singular, which is bad)
%   solver_params.numerical_diff: boolean (0 or 1)
%           1-> numerically differentiate, 0-> use analytical derivative
%should use numerical differentation to compute the Jacobian or
%use a Jacobian generated by fun. No input assumes numerical by default
%   true->fun is assumed to return [fval,J]
%   false->fun is assumed to only return fval
%OUTPUTS:
%x: the estimate of the root computed by the function
% exit_flag: an integer indicating whether or not the solver succeeded
function [X, exit_flag] = multi_newton_solver(fun,x_guess,solver_params)

%unpack values from struct (if fields in struct have been set)
    dXmin = 1e-14;
    if isfield(solver_params,'dxmin')
        dXmin = solver_params.dxmin;
    end

    ftol = 1e-14;
    if isfield(solver_params,'ftol')
        ftol = solver_params.ftol;
    end

    max_iter = 200;
    if isfield(solver_params,'max_iter')
        max_iter = solver_params.max_iter;
    end

    dXmax = 1e8;
    if isfield(solver_params,'dxmax')
        dXmax = solver_params.dxmax;
    end

    numerical_diff = 1;
    if isfield(solver_params,'numerical_diff')
        numerical_diff = solver_params.numerical_diff;
    end

    X0 = x_guess;
    
    % YOUR CODE HERE
    for i = 1:max_iter
        [f, ~] = fun(X0);
        
        
        if abs(f) < ftol
            fprintf('ftol\n');
            X = X0;
            exit_flag = 1;
            return
        end
        
        J = approximate_jacobian(fun, X0);
        dX = -J\f;

        if det(J) < ftol
            fprintf('det=0\n')
            exit_flag = 0;
            return
        end

        if abs(dX) > dXmax
            %dx = sign(dx)*dx_max;
            exit_flag = 0; 
            X = X0;
            return
        end
    
        X1=X0+dX;
    
        if abs(dX) <= dXmin
            fprintf('dxmin\n');
            X = X1;
            exit_flag = 1;
            return
        end
    
        X0 = X1;
        hold on
    end
X = X0;
exit_flag = 0;
fprintf('max_iter\n')
    
end